### ISSUE TITLE
Match all windows/applications

### ISSUE THREAD

**Issue by Vosester** [dajusc/Linux-Mouse-Keybinds#5]
I have set up my Logitech MX Master 3, it works fine with the template config on Tomb Raider.
What I want, is to map the side wheel to consistently output keys like page up/down or 8/9 on all applications.

lmkb.bind_key_to_button("", "REL_HWHEEL+", "8")       # wheel sideways left
lmkb.bind_key_to_button("", "REL_HWHEEL-", "9")       # wheel sideways right

I have tried the usual suspects like "*" etc, what is the correct regex.

**Comment by dajusc** [comment]
Hey Vosester, you can achieve that by using "_None_" instead of an app name or pid:
```Python
lmkb.bind_key_to_button(None, "REL_HWHEEL+", "8") # wheel sideways left
lmkb.bind_key_to_button(None, "REL_HWHEEL-", "9") # wheel sideways right
```
Now that I think of it, "_None_" might not have been the best choice for a special value that resembles "All". ;) 

Anyway, I think wildcards are a good idea, because they could also be used to manage dynamic window titles like "_Appname - Currently opened Project_" or quickly assign the same bindings to multiple games. I'll take this as a feature request.

**Comment by Vosester** [comment]
I feel stupid now, I actually tried "none" form the template, but it did not work.
I read the comment `# default binding for any other window `and figured it was an IF style condition, but I must have messed up the syntax as the lines provided work perfect.

I was getting ghost events, this confused games so I disabled the button output.
with xinput:
`xinput set-prop $DEVICEID "libinput Horizontal Scroll Enabled" "0"`
or
`xinput set-button-map 13 1 2 3 4 5 0 0 8 9`

It worked, but it been an analog input been output as digital it was a bit awkward. 
The side wheel has no stepping feedback, like a horizontal wheel.
For switching between binary options in games it works, but was difficult with lists as the repeated keys overshoot. 

I used the macro functions to add delay to help smooth out the repeated key presses like so.

```
lmkb.bind_key_to_button(None, "REL_HWHEEL+", ["8-", 100, "8+"]) # wheel sideways left
lmkb.bind_key_to_button(None, "REL_HWHEEL-", ["9-", 100, "9+"]) # wheel sideways right
```

I don't know what wheel data your are getting form the evdev layer, analog or digital.
Some kind of smoothing range would help.
I will keep fiddling with the macros till I get it right.
Anyways case closed thank for your help.

**Comment by dajusc** [comment]
Don't feel stupid. :) Your request resulted in a feature-/enhancement idea and useful info for others on how to disable original button functionality via xinput!

> It worked, but it been an analog input been output as digital it was a bit awkward. The side wheel has no stepping feedback, like a horizontal wheel. For switching between binary options in games it works, but was difficult with lists as the repeated keys overshoot.

Yes, the button events for the horizontal and vertical wheel actions are different compared to the "normal" buttons. While the other buttons generate seperate events for keydown (evvalu=1) and keyup (evvalu=0), the wheel events are only generated at finish/release of the physical action, whereby the evvalu is used to indicate the direction:
- wheel down one segment (evcode=8, evvalu=-1)
- wheel up one segment (evcode=8, evvalu=1)
- wheel left tilt release (evcode=6, evvalu=-1)
- wheel right tilt release (evcode=6, evvalu=1)

If I tilt my G502 mouse wheel sideways and hold it, after about one second the finish event is repetitively fired every 100 msec. This timings might only be valid for my mouse/system. Keep in mind that LMKB does not change this behavior. So if the events come in faster than your binding events are executed (e.g. because of macro-delays), they are gonna be queued and processed one after another. So what you might want/need is, that the event queue is (optionally) flushed at the end of macro execution. If this turns out to be the case, please open a separate feature request issue for this.

**Comment by Vosester** [comment]
> so if the events come in faster than your binding events are executed (e.g. because of macro-delays), they are gonna be queued and processed one after another. 

Yes I noticed this during testing, for now I have gone back to non macro output, It works well enough for what I need.
